version: "3.3"
services:
    app:
        image: sherlock_app
        ports:
          - "53864:80"
        build:
            context: .
        environment:
            DEPLOYMENT_ENVIRONMENT: production
        networks:
            frontend:
                aliases:
                    - app.sherlock
networks:
    frontend:
        external: true
